### ISSUE TITLE
Forge Authorise command not working

### ISSUE THREAD

**Issue by gbwashleybrown** [svenluijten/forge-cli#39] opened 2020-02-14 09:42 UTC
Hi,

After I run `$ forge authorize` it asks for my API key.

When I paste my key in (or even try just typing random stuff) and press enter, nothing happens.

It just stays at the 'What is your API key?` step and have to ctrl+c to get out of it...

What do I do?

**Comment by jackwh** [comment] 2020-04-14 16:58
I just submitted pull request #41, which allows passing in the API key as a parameter to the `forge authorize` command. It also updates the Symfony console libraries, which may have been contributing to the issue. Once the PR is merged it might solve your problem.

**Comment by svenluijten** [comment] 2020-05-02 10:34
@gbwashleybrown I just merged #41 and [tagged `v0.5.0`](https://github.com/svenluijten/forge-cli/releases/tag/v0.5.0) with those changes, can you verify that that fixed the issue you were experiencing?

**Comment by svenluijten** [comment] 2020-07-04 13:37
Dupe of #13, so closing for the same reason. It's an upstream issue with `symfony/console`, workaround is to pass the key as an argument to the command: `forge authorize <key>`. Alternatively, you can "manually" set the key in `~/.forge.json` (or `~/forge.json`): `{"key": "<your key here>"}`.

**Closed as completed by svenluijten** 2020-07-04 13:37 UTC
